baseurl: "" 
url: "https://zumcoin.org"

# Do not copy these files to the build folder
exclude:
 - Gemfile
 - Gemfile.lock
 - scripts
 - Rakefile
 - README.md
 - .bundle
 - vendor

gems:
 - jekyll-multiple-languages-plugin


# Localization config
languages: ["en",]
# languages: ["en",] # enable during development to see text keys at /dev/

language_names:
  at:
    short: at
    full: Österreichisches Deutsch - Bayrisch
  af:
    short: af
    full: Afrikaans
  zh:
    short: 中文
    full: 中文
  de:
    short: de
    full: Deutsch
  en:
    short: en
    full: English
  es:
    short: es
    full: Español
  fr:
    short: fr
    full: Français
  it:
    short: it
    full: Italiano
  hu:
    short: hu
    full: Magyar
  kr:
    short: kr
    full: Korean
  nl:
    short: nl
    full: Nederlands
  ru:
    short: рус
    full: Русский
  tr:
    short: tr
    full: Turkish
  pt-br:
    short: pt-br
    full: Portuguese
  cz:
    short: cz
    full: Czech
  dev:
    short: dev
    full: Development

exclude_from_localizations: ["assets", "js", "images", "css", "fonts", "scripts"]
